# Generated by Django 5.2 on 2025-04-14 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_event_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="participation_requests",
            field=models.ManyToManyField(
                blank=True, related_name="requested_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
