# Generated by Django 5.2 on 2025-04-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_event_participation_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
