# Generated by Django 5.2 on 2025-04-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_volunteerprofile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerprofile",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
