# Generated by Django 5.2 on 2025-04-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_volunteerprofile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerprofile",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="volunteerprofile",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
