# Generated by Django 5.2 on 2025-04-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_volunteerprofile_latitude_volunteerprofile_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
