# Generated by Django 5.2 on 2025-04-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_event_latitude_event_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventmanagerprofile",
            options={
                "verbose_name": "Event Manager Profile",
                "verbose_name_plural": "Event Manager Profiles",
            },
        ),
        migrations.AddField(
            model_name="eventmanagerprofile",
            name="organization_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
